---
# The develop flag is used for development-specific tasks/roles and is set to true via --extra-vars
# By default, these should not be run
develop: false

# To enable a minimal installation the following variable should be enabled:
minimal_install: false

timezone: Europe/Amsterdam

maven_repo: https://build.openconext.org/repository/public/releases
maven_snapshot_repo: https://build.openconext.org/repository/public/snapshots

ssl_key_dir: /etc/httpd/keys
env_name: "{{ env_lang }}-{{ env }}"

apache_user: apache

error_subject_prefix: "[{{ ansible_hostname }}] "

# DH-params
tls_dh_param_path: /etc/pki/tls
tls_dh_param_file: "{{ tls_dh_param_path }}/dh_params.pem"
tls_dh_param_keysize: 2048

# Some engineblock variables are shared between applications
engine_api_domain: engine-api.{{ base_domain }}
engine_api_janus_user: serviceregistry

# Some deprovision variables are shared between applications
authz_server_api_lifecycle_username: authz_server_api_lifecycle_user
teams_api_lifecycle_username: teams_api_lifecycle_user
