---
- name: Stop memcached
  service:
    name: memcached
    state: stopped
  ignore_errors: true

- name: Remove memcached
  yum:
    name: memcached
    state: absent

- name: Remove serviceregistry application
  shell: rm -rf /opt/openconext/OpenConext-serviceregistry* /opt/openconext/builds/janus* /opt/openconext/builds/simplesamlphp*

- name: Remove serviceregistry files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
      - /etc/httpd/conf.d/serviceregistry.conf
      - /etc/php-fpm.d/serviceregistry-pool.conf
      - /var/lib/openconext/session/serviceregistry/
      - /var/log/janus-ssp/
      - /var/cache/janus-ssp/
  notify:
    - "restart httpd"
    - "restart php-fpm"
