- name: install rsyslog
  yum:
    name:
      - rsyslog
      - rsyslog-gnutls
      - rsyslog-relp
    state: present
  notify:
  - "restart rsyslog"

- name: place rsyslog CA file
  copy:
    src: "{{ inventory_dir }}/files/certs/rsyslog_ca.pem"
    dest: "{{ rsyslog_ca }}"
  when:
    - remote_syslog_host is defined
  notify:
    - "restart rsyslog"

# We need a key and client certificate to when using RELP
- name: put rsyslog client key
  copy:
    content: "{{ rsyslogclientkey }}"
    dest: "/etc/pki/rsyslog/rsyslogclient.key"
    mode: 0400
    owner: root
  when: 
    - rsyslog_remote_server_relp is defined
  no_log: true
  notify:
    - "restart rsyslog"

- name: put rsyslog client certificate
  copy:
    src: "{{ inventory_dir }}/files/certs/rsyslog/rsyslogclient.crt"
    dest: "/etc/pki/rsyslog/rsyslogclient.crt"
    mode: 0744
    owner: root
    group: adm
  when: 
    - rsyslog_remote_server_relp is defined
  notify:
    - "restart rsyslog"

- name: put rsyslog CA file (new location) 
  copy: 
    src: "{{ inventory_dir }}/files/certs/rsyslog/rsyslogclientca.crt"
    dest: "/etc/pki/rsyslog/rsyslogclientca.crt"
    mode: 0744
    owner: root
    group: adm
  when: 
    - rsyslog_remote_server_relp is defined

- name: put ryslog config file
  template:
    src: "rsyslog.conf.j2"
    dest: "/etc/rsyslog.conf"
  notify:
    - "restart rsyslog"

- name: include tasks for central syslog server
  include: rsyslog_central.yml
  when:  "'sysloghost' in group_names"
