---
# The server uses a different set of keys as the client
- name: put rsyslog server key
  copy:
    content: "{{ rsyslogserverkey }}" 
    dest: "/etc/pki/rsyslog/rsyslogserver.key"
    mode: 0400
    owner: root
  no_log: true

- name: put rsyslog client certificate
  copy:
    src: "{{ inventory_dir }}/files/certs/rsyslog/rsyslogserver.crt"
    dest: "/etc/pki/rsyslog/rsyslogserver.crt"
    mode: 0644
    owner: root
    group: adm

- name: place rsyslog CA file
  copy:
    src: "{{ inventory_dir }}/files/certs/rsyslog_ca.pem"
    dest: "{{ rsyslog_ca }}" 
    mode: 0644

- name: Create directories to keep configuration file
  file:
    path: "/etc/rsyslog.d/{{ item }}"
    owner: root
    mode: 0755
    state: directory
  with_items:
    - listeners
    - rulesets
    - templates

- name: Create sc template configurations
  template: 
    src: sc_template.conf.j2
    dest: /etc/rsyslog.d/templates/{{ item.name }}.conf
  with_items: "{{ rsyslog_environments.sc }}"

- name: Create sa template configurations
  template: 
    src: sa_template.conf.j2
    dest: /etc/rsyslog.d/templates/{{ item.name }}.conf
  with_items: "{{ rsyslog_environments.sa }}"

- name: Create sc ruleset configurations
  template: 
    src: sc_ruleset.conf.j2
    dest: /etc/rsyslog.d/rulesets/{{ item.name }}.conf
  with_items: "{{ rsyslog_environments.sc }}"

- name: Create sa ruleset configurations
  template: 
    src: sa_ruleset.conf.j2
    dest: /etc/rsyslog.d/rulesets/{{ item.name }}.conf
  with_items: "{{ rsyslog_environments.sa }}"

- name: Create sc listener configurations
  template: 
    src: listener.conf.j2
    dest: /etc/rsyslog.d/listeners/{{ item.name }}.conf
  with_items: "{{ rsyslog_environments.sc }}"

- name: Create sa listener configurations
  template: 
    src: listener.conf.j2
    dest: /etc/rsyslog.d/listeners/{{ item.name }}.conf
  with_items: "{{ rsyslog_environments.sa }}"
