---
- hosts: all
  gather_facts: no
  tasks:
  - name: Read vars from secrets file
    include_vars: "{{ secrets_file }}"
    tags:
      - always

- hosts: all
  gather_facts: yes
  become: true
  roles:
    - { role: common, tags: ['common'] }
#    - { role: '{{ inventory_dir }}/../roles/surfconext_common',   tags: ['surfconext_common'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: rsyslog, tags: ['rsyslog'] }
  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: loadbalancer
  gather_facts: no
  become: true
  roles:
    - { role: haproxy, tags: ['lb'] }
    - { role: tls, tags: ['tls'] }

- hosts: php-apps:java-apps
  gather_facts: yes
  become: true
  roles:
    - { role: httpd, tags: ['httpd'] }

- hosts: dbcluster
  gather_facts: yes
  become: true
  roles:
    - { role: galera, tags: ['galera'] }

- hosts: dbcluster_nodes
  gather_facts: yes
  become: true
  roles:
    - { role: keepalived, tags: ['keepalived'] }
    - { role: galera_create_users, tags: ['galera', 'galera_create_users'] } 

- hosts: mongo_servers
  gather_facts: yes
  become: true
  roles:
    - { role: mongo, tags: ['mongo'] }

- hosts: php-apps
  gather_facts: yes
  become: true
  vars:
    env_lang: php
  roles:
    - { role: php56fpm,          tags: ['php56fpm'] }
    - { role: static,            tags: ['static'  ] }
    - { role: openconext-common, tags: ['eb','sr','profile'] }
    - { role: engineblock,       tags: ['eb'     ] }
    - { role: janus,             tags: ['sr'      ] }
    - { role: profile,           tags: ['profile' ] }
#    - { role: '{{ inventory_dir }}/../roles/spform',            tags: ['spform' ] }

  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: java-apps
  gather_facts: true
  become: true
  vars:
    env_lang: java
  roles:
    - { role: tomcat,                       tags: ['tomcat'] }
    - { role: java,                         tags: ['java'] }
    - { role: shibboleth,                   tags: ['shib'   ] }
    - { role: teams-gui,                    tags: ['teams', 'teams-gui'  ] }
    - { role: teams-server,                 tags: ['teams', 'teams-server'  ] }
    - { role: mujina-idp,                   tags: ['mujina','mujina-idp' ] }
    - { role: mujina-sp,                    tags: ['mujina','mujina-sp' ] }
    - { role: authz-server,                 tags: ['oauth', 'authz-server'    ] }
    - { role: authz-admin,                  tags: ['oauth', 'authz-admin'     ] }
    - { role: voot,                         tags: ['oauth', 'voot'            ] }
    - { role: authz-playground,             tags: ['oauth', 'authz-playground'] }
    - { role: pdp-gui,                      tags: ['pdp', 'pdp-gui'] }
    - { role: pdp-server,                   tags: ['pdp', 'pdp-server'] }
    - { role: oidc,                         tags: ['oidc'] }
    - { role: attribute-aggregation-gui,    tags: ['attribute-aggregation', 'attribute-aggregation-gui'] }
    - { role: attribute-aggregation-server, tags: ['attribute-aggregation', 'attribute-aggregation-server'] }
    - { role: manage-gui,                   tags: ['manage', 'manage-gui'] }
    - { role: manage-server,                tags: ['manage', 'manage-server'] }
    - { role: attribute-mapper,             tags: ['attribute-mapper'] }
    - { role: eduproxy,                     tags: ['eduproxy'] }
    - { role: monitoring-tests,             tags: ['monitoring-tests'] }
    - { role: remove-grouper,               tags: ['remove-grouper'] }
    - { role: remove-metadata-exporter,     tags: ['remove-metadata-exporter'] }
  handlers:
    - include: roles/httpd/handlers/main.yml
