- name: copy json
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{ item }}"
  with_items:
    - saml20_idp.json
    - saml20_sp.json

- name: import metadata manage
  command: mongoimport --db {{ manage.mongo_database }} --username {{ manage.mongo_user }} --password {{ manage.mongo_password }} --collection {{ item.coll }}  --file /tmp/{{ item.coll }}.json
  with_items:
    - { coll:  "saml20_idp"}
    - { coll:  "saml20_sp"}
  run_once: true
  changed_when: false


- name: Include vars of manage-server
  include_vars:
    file: ../../manage-server/vars/main.yml

# Open TCP port for manage
- iptables_raw:
    name: allow_tcp_port_manage
    rules: "-A INPUT -p tcp -m tcp --dport {{ springapp_tcpport }} -j ACCEPT"

- name: push metadata eb
  uri:
    url: "http://localhost:{{ springapp_tcpport }}/internal/push"
    method: GET
    user: "{{ manage.apiUsers[2].name }}"
    password: "{{ manage.apiUsers[2].password }}"
    force_basic_auth: yes
    run_once: true
    status_code: 200
  changed_when: false
