# The global variable file mongodb installation

# The port for mongo server
mongod_port: 27017

# The default hostname for mongo:
mongo_hostname: localhost

# The password for admin user
mongo_admin_pass: "{{ mongo_admin_password }}"

# The name of the replication set
replica_set_name: "{{ instance_name }}"

# When using tls, use this root CA certificate

mongo_tls_ca: mongo.{{ base_domain }}_ca.pem

# Some default switches
mongo_primary: false
mongo_tls: false
mongo_cluster: false

# Default cache size
mongo_cache_size: 1

# Add a database
mongo:
  manage_user: managerw
  manage_password: "{{ mongo_passwords.manage }}"
  manage_database: manage

