# Install the "REMI" repo which contain newer php packages that override the default
# that come with the distro (CentOS7: 5.4; CentOS6: 5.3)
- name: check for presence of the remi repository file
  stat:
    path: "/etc/yum.repos.d/remi.repo"
  register: remi_config

- name: Install REMI repo
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present
  when:
    - remi_config.stat.exists == False

- name: Enable REMI repo
  copy:
      src: remi.repo
      dest: /etc/yum.repos.d/remi.repo
  when:
    - remi_config.stat.exists == False

- name: Install php-(cli,fpm), composer
  yum:
    name:
      - php-fpm
      - php-cli
      - php-pecl-apcu
      - php-curl
      - php-mbstring
      - php-mysql
      - php-soap
      - php-xml
      - php-gd
      - composer
    state: present

- name: check for presence of the remi 72 repository file
  stat:
    path: "/etc/yum.repos.d/remi-php72.repo"
  register: remi_php72_config

- name: Enable REMI 72 repo
  copy:
      src: remi-php72.repo
      dest: /etc/yum.repos.d/remi-php72.repo
  when:
    - remi_php72_config.stat.exists == False

- name: Install php-(cli,fpm) 7.2
  yum:
    name:
      - php72-php-fpm
      - php72-php-cli
      - php72-php-pecl-apcu
      - php72-php-curl
      - php72-php-mbstring
      - php72-php-mysql
      - php72-php-soap
      - php72-php-xml
      - php72-php-gd
    state: present

- name: Enable php-fpm
  service:
    name: php-fpm
    enabled: yes

- name: Install custom PHP configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/php.d/{{ item }}"
  with_items:
    - 40-apcu.ini
    - openconext.ini
  notify:
    - "restart php-fpm"

- name: Install custom PHP configuration for 7.2
  template:
    src: "{{ item }}.j2"
    dest: "/etc/opt/remi/php72/php.d/{{ item }}"
  with_items:
    - 40-apcu.ini
    - openconext.ini
  notify:
    - "restart php72-php-fpm"

- name: Install PHP debug extensions
  yum:
    name:
      - php-pecl-xdebug
      - php72-php-pecl-xdebug
    state: present
  when:
    - develop | bool

- name: Configure PHP Xdebug
  template:
    src: "xdebug.ini.j2"
    dest: "/etc/php.d/15-xdebug.ini"
  when:
    - develop | bool
  notify:
    - "restart php-fpm"

- name: Configure PHP Xdebug for 7.2
  template:
    src: "xdebug.ini.j2"
    dest: "/etc/opt/remi/php72/php.d/15-xdebug.ini"
  when:
    - develop | bool
  notify:
    - "restart php72-php-fpm"

- name: Put /etc/php-fpm.conf
  copy:
    src: "php-fpm.conf"
    dest: "/etc/php-fpm.conf"
  notify:
    - "restart php-fpm"

- name: Put 7.2 php-fpm.conf
  copy:
    src: "php72-fpm.conf"
    dest: "/etc/opt/remi/php72/php-fpm.conf"
  notify:
    - "restart php72-php-fpm"

- name: Put 7.2 php-fpm www pool conf
  copy:
    src: "www.conf"
    dest: "/etc/opt/remi/php72/php-fpm.d/www.conf"
  notify:
    - "restart php72-php-fpm"

- name: Enable php-fpm
  service:
    name: php-fpm
    enabled: yes

- name: Enable php72-php-fpm
  service:
    name: php72-php-fpm
    enabled: yes

# Set mode to a+x so components can access their subdirectories under session/
- name: Create directory for vhosts to store PHP sessions
  file:
    path: "{{ php_session_dir }}"
    state: directory
    mode: 0771
