---
manage_dir: /opt/manage
manage_snapshot_timestamp: ''
manage_local_jar: ''
manage_jar: manage-current.jar
manage_random_source: 'file:///dev/urandom'
manage_cronjobmaster: false
manage_disclaimer_background_color: skyblue
manage_disclaimer_content: OC
